name = "gracefulcare-api"
main = "worker.js"
compatibility_date = "2023-03-14"

[vars]
MONGODB_URI = "your-mongodb-uri"

[[d1_databases]]
binding = "DB"
database_name = "gracefulcare"
database_id = "your-database-id" 