name = "gracefulcare-api"
main = "worker.js"
compatibility_date = "2023-03-14"

[vars]
R2_PUBLIC_DOMAIN = "111ce057f7b2b1eb01636893efe1aa24.r2.cloudflarestorage.com"

[[r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "fileuploader"
preview_bucket_name = "fileuploader" 